import type { Item } from '../types'

// Seeded from the real historical item master (union of both branch workbooks)
// so the Item Master isn't empty on first run. Freely editable in the app.
export const SEED_ITEMS: Item[] = [
  { code: 'I001', name: 'achubundi', pricePerKg: 280 },
  { code: 'I002', name: 'agra pan', pricePerKg: 25 },
  { code: 'I003', name: 'ajmeer kalakan', pricePerKg: 480 },
  { code: 'I004', name: 'ajmeer kalakan (cake dimma)', pricePerKg: 480 },
  { code: 'I005', name: 'akbar badusha', pricePerKg: 280 },
  { code: 'I006', name: 'angeer kalakan', pricePerKg: 480 },
  { code: 'I007', name: 'annamayya laddu', pricePerKg: 640 },
  { code: 'I008', name: 'arishelu', pricePerKg: 280 },
  { code: 'I009', name: 'atukulu', pricePerKg: 280 },
  { code: 'I010', name: 'badam malai kalakan', pricePerKg: 480 },
  { code: 'I011', name: 'badam rolls', pricePerKg: 480 },
  { code: 'I012', name: 'badusha', pricePerKg: 280 },
  { code: 'I013', name: 'basin laddu', pricePerKg: 400 },
  { code: 'I014', name: 'bellam halwa', pricePerKg: 400 },
  { code: 'I015', name: 'bobbatlu', pricePerKg: 280 },
  { code: 'I016', name: 'bundi', pricePerKg: 280 },
  { code: 'I017', name: 'burfi varieties', pricePerKg: 480 },
  { code: 'I018', name: 'carrot kalakan', pricePerKg: 480 },
  { code: 'I019', name: 'centre bournvita kalakan', pricePerKg: 480 },
  { code: 'I020', name: 'chakralu', pricePerKg: 280 },
  { code: 'I021', name: 'chandrakala', pricePerKg: 320 },
  { code: 'I022', name: 'cheka pakodi', pricePerKg: 280 },
  { code: 'I023', name: 'chekkalu', pricePerKg: 280 },
  { code: 'I024', name: 'chekodi', pricePerKg: 280 },
  { code: 'I025', name: 'chinna khaja', pricePerKg: 280 },
  { code: 'I026', name: 'coconut rasagulla', pricePerKg: 480 },
  { code: 'I027', name: 'dry fruit katli', pricePerKg: 1200 },
  { code: 'I028', name: 'dryfruit halwa', pricePerKg: 480 },
  { code: 'I029', name: 'dryfruit laddu', pricePerKg: 480 },
  { code: 'I030', name: 'gulab jam', pricePerKg: 480 },
  { code: 'I031', name: 'gulab jam with liquid', pricePerKg: 30 },
  { code: 'I032', name: 'gulabjam (with pakam)', pricePerKg: 30 },
  { code: 'I033', name: 'horlick pak', pricePerKg: 480 },
  { code: 'I034', name: 'horlicks kalakan', pricePerKg: 480 },
  { code: 'I035', name: 'jangri', pricePerKg: 320 },
  { code: 'I036', name: 'jug kalakan', pricePerKg: 480 },
  { code: 'I037', name: 'kaja', pricePerKg: 280 },
  { code: 'I038', name: 'kajjara', pricePerKg: 280 },
  { code: 'I039', name: 'kajji kayalu', pricePerKg: 280 },
  { code: 'I040', name: 'kakinada kaja', pricePerKg: 360 },
  { code: 'I041', name: 'kala jam', pricePerKg: 480 },
  { code: 'I042', name: 'kalakan', pricePerKg: 400 },
  { code: 'I043', name: 'kara khaju', pricePerKg: 1000 },
  { code: 'I044', name: 'karjoora kalakan', pricePerKg: 480 },
  { code: 'I045', name: 'kashmeer kalakan', pricePerKg: 480 },
  { code: 'I046', name: 'khaju burfi', pricePerKg: 1000 },
  { code: 'I047', name: 'khaju kalakan', pricePerKg: 480 },
  { code: 'I048', name: 'khaju mithai', pricePerKg: 1000 },
  { code: 'I049', name: 'khaju pakodi', pricePerKg: 360 },
  { code: 'I050', name: 'khaju perpu', pricePerKg: 480 },
  { code: 'I051', name: 'khaju rolls', pricePerKg: 1000 },
  { code: 'I052', name: 'kharjoora kalakan', pricePerKg: 480 },
  { code: 'I053', name: 'kommuulu', pricePerKg: 280 },
  { code: 'I054', name: 'kowha (round)', pricePerKg: 320 },
  { code: 'I055', name: 'kowha (small)', pricePerKg: 320 },
  { code: 'I056', name: 'kowha gummadikaya', pricePerKg: 480 },
  { code: 'I057', name: 'laddu', pricePerKg: 280 },
  { code: 'I058', name: 'looze kalakan', pricePerKg: 400 },
  { code: 'I059', name: 'madras murukulu', pricePerKg: 280 },
  { code: 'I060', name: 'malai chaps(kowha)', pricePerKg: 480 },
  { code: 'I061', name: 'masala pakodi', pricePerKg: 280 },
  { code: 'I062', name: 'metha pakodi', pricePerKg: 280 },
  { code: 'I063', name: 'milk laddu', pricePerKg: 480 },
  { code: 'I064', name: 'milk pak', pricePerKg: 480 },
  { code: 'I065', name: 'milk patti', pricePerKg: 320 },
  { code: 'I066', name: 'mixture', pricePerKg: 280 },
  { code: 'I067', name: 'mokkajonna chips', pricePerKg: 280 },
  { code: 'I068', name: 'mothi pack', pricePerKg: 400 },
  { code: 'I069', name: 'mothichur laddu', pricePerKg: 400 },
  { code: 'I070', name: 'mova kajjikaya', pricePerKg: 480 },
  { code: 'I071', name: 'muruku', pricePerKg: 280 },
  { code: 'I072', name: 'mysoor pak', pricePerKg: 280 },
  { code: 'I073', name: 'nammak para', pricePerKg: 280 },
  { code: 'I074', name: 'palli chekka', pricePerKg: 280 },
  { code: 'I075', name: 'palli pakodi', pricePerKg: 280 },
  { code: 'I076', name: 'pallilu', pricePerKg: 280 },
  { code: 'I077', name: 'panchadara gavvalu', pricePerKg: 280 },
  { code: 'I078', name: 'paneer', pricePerKg: 600 },
  { code: 'I079', name: 'patisha rolls', pricePerKg: 520 },
  { code: 'I080', name: 'pedda chekodi', pricePerKg: 280 },
  { code: 'I081', name: 'pikka kowha', pricePerKg: 280 },
  { code: 'I082', name: 'pineapple kalakan', pricePerKg: 480 },
  { code: 'I083', name: 'pineapple rolls', pricePerKg: 480 },
  { code: 'I084', name: 'pink / yellow rasagulla', pricePerKg: 480 },
  { code: 'I085', name: 'pistha kalakan', pricePerKg: 480 },
  { code: 'I086', name: 'rasa malai', pricePerKg: 30 },
  { code: 'I087', name: 'rusagulla varieties', pricePerKg: 480 },
  { code: 'I088', name: 'sadha laddu', pricePerKg: 320 },
  { code: 'I089', name: 'sanna poosa', pricePerKg: 280 },
  { code: 'I090', name: 'sannaboondi mixture', pricePerKg: 320 },
  { code: 'I091', name: 'seethaphal/apple (kowha)', pricePerKg: 480 },
  { code: 'I092', name: 'side chocolate kalakan', pricePerKg: 480 },
  { code: 'I093', name: 'simla rolls(kowha)', pricePerKg: 480 },
  { code: 'I094', name: 'small cham cham (white)', pricePerKg: 480 },
  { code: 'I095', name: 'sompatti', pricePerKg: 320 },
  { code: 'I096', name: 'special mixture', pricePerKg: 320 },
  { code: 'I097', name: 'sugar free kalakan', pricePerKg: 760 },
  { code: 'I098', name: 'sugar free laddu', pricePerKg: 680 },
  { code: 'I099', name: 'sugar free sunniundalu', pricePerKg: 760 },
  { code: 'I100', name: 'sunni undalu', pricePerKg: 400 },
  { code: 'I101', name: 'thapeshwaram khaja', pricePerKg: 280 },
  { code: 'I102', name: 'vam poosa', pricePerKg: 280 },
  { code: 'I103', name: 'white kalakan', pricePerKg: 440 },
]
